apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
      {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 4 }}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: {{ .Values.service.portName}}
      interval: 30s
      scrapeTimeout: 10s