### 1. Створити нову подію (POST)
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Подія для видалення",
  "description": "Зараз ми її видалимо"
}

### ------------------------------
### 2. Отримати всі події (GET)
GET http://localhost:8080/api/events

### ------------------------------
### 3. Отримати ОДНУ подію (GET by ID) - УСПІХ
# Спочатку виконайте запит #1
GET http://localhost:8080/api/events/1

### ------------------------------
### 5. ОНОВИТИ подію (PUT by ID)
PUT http://localhost:8080/api/events/1
Content-Type: application/json

{
  "title": "ОНОВЛЕНИЙ Концерт",
  "description": "Опис теж оновився!"
}

### ------------------------------
### 6. ВИДАЛИТИ подію (DELETE by ID)
# Спочатку виконайте запит #1
DELETE http://localhost:8080/api/events/3

### Отримати всіх користувачів
GET http://localhost:8080/api/users

### ------------------------------
### 7. Зареєструвати нового користувача
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "roman",
  "password": "mySecurePassword123"
}