global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'SpotlyWebApp'

rule_files:
  - 'node-exporter.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['10.0.1.252:9100']
        labels:
          instance: 'backend'
      - targets: [ 'node_exporter:9100' ]
        labels:
          instance: 'monitoring'
      - targets: ['10.0.101.49:9100']
        labels:
          instance: 'frontend'


  - job_name: 'cadvisor'
    static_configs:
      - targets: [ '10.0.1.252:8081' ]
        labels:
          instance: 'backend'
      - targets: [ '10.0.101.49:8081' ]
        labels:
          instance: 'frontend'
