route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 60m
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - send_resolved: true
    bot_token: '7624834838:AAF8_4jmhR1hkOdemfQccWTZJwbvkXSR5Yg'
    chat_id: 532142381