spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

jwt.secret.key=bXktc3VwZXItc2VjcmV0LWtleS1mb3Itc3BvdGx5LWFwcC0xMjM0NTY3ODktYW5kLW1vcmUtcmFuZG9tLXN0dWZm
server.forward-headers-strategy=native
server.address=0.0.0.0
server.port=8080

# --- Monitoring via Prometheus ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.enable.all=true
management.prometheus.metrics.export.enabled=true
spring.datasource.hikari.metrics.enabled=true

# --- OAuth2 Configuration (Google) ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

frontend.url=http://spotly.mylabstep.com
frontend.redirect.url=http://spotly.mylabstep.com/login-success

# --- Logging Configuration ---
logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.spotly.backend=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

logging.file.name=logs/app.log
logging.file.path=logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %logger{36} - %msg%n%ex{full}
spring.output.ansi.enabled=ALWAYS

# ======== AWS S3 CONFIGURATION ========
aws.s3.bucket-name=spotly-user-avatars-dev
aws.s3.region=eu-west-1

aws.s3.access-key-id=${AWS_ACCESS_KEY_ID}
aws.s3.secret-access-key=${AWS_SECRET_ACCESS_KEY}



