apiVersion: v2
name: Promstack
description: Promstack
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "65.*"
    repository: "https://prometheus-community.github.io/helm-charts"

