kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: neoadmin
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 5Gi
    dashboards:
      default:
        kubernetes-overview: {}
  prometheus:
    prometheusSpec:
      retention: 7d
      serviceMonitorSelectorNilUsesHelmValues: false
  alertmanager:
    enabled: false

#alertmanager:
#  enabled: true
#  config:
#    global: {}
#    route:
#      group_by: ['alertname']
#      group_wait: 30s
#      group_interval: 5m
#      repeat_interval: 12h
#      receiver: 'pager'
#    receivers:
#      - name: 'pager'
#        email_configs:
#          - to: 'oncall@example.org'
#            from: 'alertmanager@example.org'
#            smarthost: 'smtp.example.org:587'
#            auth_username: 'alertmanager'
#            auth_identity: 'alertmanager'

