name: Frontend Build and Deploy

on:
  push:
    branches:
      - develop
    paths:
      - 'Frontend/**'
      - '.github/workflows/deploy_frontend.yml'
  workflow_dispatch:

jobs:
  validate:
    name: Validate React
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Frontend/WebApp

      - name: Run lint
        run: npm run lint
        working-directory: Frontend/WebApp

  deploy:
    runs-on: [ self-hosted, Linux, X64, frontend ]
    needs: validate
    steps:
      - name: Deploy frontend to server
        run: |
          cd /home/${{ secrets.SSH_USER }}/SpotlyWebApp
          git pull 
          git switch develop
          cd Frontend

          echo "Starting Docker Compose..."
          docker compose down
          docker compose up -d --build
