name: Build & Deploy Spring Boot App

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'    
      - '.github/workflows/deploy_backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, Linux, X64, frontend ]
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/SpotlyWebApp
            git pull 
            git switch develop
            cd /backend
            
            echo "Exporting environment variables..."
            export DB_URL='${{ secrets.DB_URL }}'
            export DB_USERNAME='${{ secrets.DB_USERNAME }}'
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            export JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'
            export SPRING_PROFILES_ACTIVE=dev
            
            echo "Starting Docker Compose..."
            docker compose -f docker-compose.yml up -d