name: Frontend Build and Deploy

on:
  push:
    branches:
      - develop
    #paths:
    # - 'frontend/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux, X64, frontend]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: develop

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      working-directory: Frontend 

    - name: Run Production Build
      run: npm run build
      working-directory: Frontend
      env:
        CI: true

    - name: Copy Built Files to NGINX Root
      run: |
        # Копіюємо з папки збірки всередині Frontend (Frontend/dist/)
        sudo rsync -av --delete dist/ /var/www/frontend_app/
      working-directory: Frontend

    - name: Restart NGINX Service
      run: sudo systemctl restart nginx